import colors from './colors.js';

export const tailwindColors = {
    ...colors,
    inherit: 'inherit',
    current: 'currentColor',
    transparent: 'transparent',
    black: '#000',
    white: '#fff',

    primary: {
        50: 'hsl(var(--color-primary-50) / <alpha-value>)',
        100: 'hsl(var(--color-primary-100) / <alpha-value>)',
        200: 'hsl(var(--color-primary-200) / <alpha-value>)',
        300: 'hsl(var(--color-primary-300) / <alpha-value>)',
        400: 'hsl(var(--color-primary-400) / <alpha-value>)',
        500: 'hsl(var(--color-primary-500) / <alpha-value>)',
        600: 'hsl(var(--color-primary-600) / <alpha-value>)',
        700: 'hsl(var(--color-primary-700) / <alpha-value>)',
        800: 'hsl(var(--color-primary-800) / <alpha-value>)',
        900: 'hsl(var(--color-primary-900) / <alpha-value>)',
        950: 'hsl(var(--color-primary-950) / <alpha-value>)',
    },
    secondary: {
        50: 'hsl(var(--color-secondary-50) / <alpha-value>)',
        100: 'hsl(var(--color-secondary-100) / <alpha-value>)',
        200: 'hsl(var(--color-secondary-200) / <alpha-value>)',
        300: 'hsl(var(--color-secondary-300) / <alpha-value>)',
        400: 'hsl(var(--color-secondary-400) / <alpha-value>)',
        500: 'hsl(var(--color-secondary-500) / <alpha-value>)',
        600: 'hsl(var(--color-secondary-600) / <alpha-value>)',
        700: 'hsl(var(--color-secondary-700) / <alpha-value>)',
        800: 'hsl(var(--color-secondary-800) / <alpha-value>)',
        900: 'hsl(var(--color-secondary-900) / <alpha-value>)',
        950: 'hsl(var(--color-secondary-950) / <alpha-value>)',
    },
    tertiary: {
        50: 'hsl(var(--color-tertiary-50) / <alpha-value>)',
        100: 'hsl(var(--color-tertiary-100) / <alpha-value>)',
        200: 'hsl(var(--color-tertiary-200) / <alpha-value>)',
        300: 'hsl(var(--color-tertiary-300) / <alpha-value>)',
        400: 'hsl(var(--color-tertiary-400) / <alpha-value>)',
        500: 'hsl(var(--color-tertiary-500) / <alpha-value>)',
        600: 'hsl(var(--color-tertiary-600) / <alpha-value>)',
        700: 'hsl(var(--color-tertiary-700) / <alpha-value>)',
        800: 'hsl(var(--color-tertiary-800) / <alpha-value>)',
        900: 'hsl(var(--color-tertiary-900) / <alpha-value>)',
        950: 'hsl(var(--color-tertiary-950) / <alpha-value>)',
    },
    danger: {
        50: 'hsl(var(--color-danger-50) / <alpha-value>)',
        100: 'hsl(var(--color-danger-100) / <alpha-value>)',
        200: 'hsl(var(--color-danger-200) / <alpha-value>)',
        300: 'hsl(var(--color-danger-300) / <alpha-value>)',
        400: 'hsl(var(--color-danger-400) / <alpha-value>)',
        500: 'hsl(var(--color-danger-500) / <alpha-value>)',
        600: 'hsl(var(--color-danger-600) / <alpha-value>)',
        700: 'hsl(var(--color-danger-700) / <alpha-value>)',
        800: 'hsl(var(--color-danger-800) / <alpha-value>)',
        900: 'hsl(var(--color-danger-900) / <alpha-value>)',
        950: 'hsl(var(--color-danger-950) / <alpha-value>)',
    },
    warn: {
        50: 'hsl(var(--color-warn-50) / <alpha-value>)',
        100: 'hsl(var(--color-warn-100) / <alpha-value>)',
        200: 'hsl(var(--color-warn-200) / <alpha-value>)',
        300: 'hsl(var(--color-warn-300) / <alpha-value>)',
        400: 'hsl(var(--color-warn-400) / <alpha-value>)',
        500: 'hsl(var(--color-warn-500) / <alpha-value>)',
        600: 'hsl(var(--color-warn-600) / <alpha-value>)',
        700: 'hsl(var(--color-warn-700) / <alpha-value>)',
        800: 'hsl(var(--color-warn-800) / <alpha-value>)',
        900: 'hsl(var(--color-warn-900) / <alpha-value>)',
        950: 'hsl(var(--color-warn-950) / <alpha-value>)',
    },
    success: {
        50: 'hsl(var(--color-success-50) / <alpha-value>)',
        100: 'hsl(var(--color-success-100) / <alpha-value>)',
        200: 'hsl(var(--color-success-200) / <alpha-value>)',
        300: 'hsl(var(--color-success-300) / <alpha-value>)',
        400: 'hsl(var(--color-success-400) / <alpha-value>)',
        500: 'hsl(var(--color-success-500) / <alpha-value>)',
        600: 'hsl(var(--color-success-600) / <alpha-value>)',
        700: 'hsl(var(--color-success-700) / <alpha-value>)',
        800: 'hsl(var(--color-success-800) / <alpha-value>)',
        900: 'hsl(var(--color-success-900) / <alpha-value>)',
        950: 'hsl(var(--color-success-950) / <alpha-value>)',
    },

    gray: {
        50: 'hsl(var(--color-gray-50) / <alpha-value>)',
        100: 'hsl(var(--color-gray-100) / <alpha-value>)',
        200: 'hsl(var(--color-gray-200) / <alpha-value>)',
        300: 'hsl(var(--color-gray-300) / <alpha-value>)',
        400: 'hsl(var(--color-gray-400) / <alpha-value>)',
        500: 'hsl(var(--color-gray-500) / <alpha-value>)',
        600: 'hsl(var(--color-gray-600) / <alpha-value>)',
        700: 'hsl(var(--color-gray-700) / <alpha-value>)',
        800: 'hsl(var(--color-gray-800) / <alpha-value>)',
        900: 'hsl(var(--color-gray-900) / <alpha-value>)',
        950: 'hsl(var(--color-gray-950) / <alpha-value>)',
    },

    primarytext: {
        50: 'hsl(var(--color-primarytext-50) / <alpha-value>)',
        100: 'hsl(var(--color-primarytext-100) / <alpha-value>)',
        200: 'hsl(var(--color-primarytext-200) / <alpha-value>)',
        300: 'hsl(var(--color-primarytext-300) / <alpha-value>)',
        400: 'hsl(var(--color-primarytext-400) / <alpha-value>)',
        500: 'hsl(var(--color-primarytext-500) / <alpha-value>)',
        600: 'hsl(var(--color-primarytext-600) / <alpha-value>)',
        700: 'hsl(var(--color-primarytext-700) / <alpha-value>)',
        800: 'hsl(var(--color-primarytext-800) / <alpha-value>)',
        900: 'hsl(var(--color-primarytext-900) / <alpha-value>)',
        950: 'hsl(var(--color-primarytext-950) / <alpha-value>)',
    },
    secondarytext: {
        50: 'hsl(var(--color-secondarytext-50) / <alpha-value>)',
        100: 'hsl(var(--color-secondarytext-100) / <alpha-value>)',
        200: 'hsl(var(--color-secondarytext-200) / <alpha-value>)',
        300: 'hsl(var(--color-secondarytext-300) / <alpha-value>)',
        400: 'hsl(var(--color-secondarytext-400) / <alpha-value>)',
        500: 'hsl(var(--color-secondarytext-500) / <alpha-value>)',
        600: 'hsl(var(--color-secondarytext-600) / <alpha-value>)',
        700: 'hsl(var(--color-secondarytext-700) / <alpha-value>)',
        800: 'hsl(var(--color-secondarytext-800) / <alpha-value>)',
        900: 'hsl(var(--color-secondarytext-900) / <alpha-value>)',
        950: 'hsl(var(--color-secondarytext-950) / <alpha-value>)',
    },
    tertiarytext: {
        50: 'hsl(var(--color-tertiarytext-50) / <alpha-value>)',
        100: 'hsl(var(--color-tertiarytext-100) / <alpha-value>)',
        200: 'hsl(var(--color-tertiarytext-200) / <alpha-value>)',
        300: 'hsl(var(--color-tertiarytext-300) / <alpha-value>)',
        400: 'hsl(var(--color-tertiarytext-400) / <alpha-value>)',
        500: 'hsl(var(--color-tertiarytext-500) / <alpha-value>)',
        600: 'hsl(var(--color-tertiarytext-600) / <alpha-value>)',
        700: 'hsl(var(--color-tertiarytext-700) / <alpha-value>)',
        800: 'hsl(var(--color-tertiarytext-800) / <alpha-value>)',
        900: 'hsl(var(--color-tertiarytext-900) / <alpha-value>)',
        950: 'hsl(var(--color-tertiarytext-950) / <alpha-value>)',
    },
    dangertext: {
        50: 'hsl(var(--color-dangertext-50) / <alpha-value>)',
        100: 'hsl(var(--color-dangertext-100) / <alpha-value>)',
        200: 'hsl(var(--color-dangertext-200) / <alpha-value>)',
        300: 'hsl(var(--color-dangertext-300) / <alpha-value>)',
        400: 'hsl(var(--color-dangertext-400) / <alpha-value>)',
        500: 'hsl(var(--color-dangertext-500) / <alpha-value>)',
        600: 'hsl(var(--color-dangertext-600) / <alpha-value>)',
        700: 'hsl(var(--color-dangertext-700) / <alpha-value>)',
        800: 'hsl(var(--color-dangertext-800) / <alpha-value>)',
        900: 'hsl(var(--color-dangertext-900) / <alpha-value>)',
        950: 'hsl(var(--color-dangertext-950) / <alpha-value>)',
    },
    warntext: {
        50: 'hsl(var(--color-warntext-50) / <alpha-value>)',
        100: 'hsl(var(--color-warntext-100) / <alpha-value>)',
        200: 'hsl(var(--color-warntext-200) / <alpha-value>)',
        300: 'hsl(var(--color-warntext-300) / <alpha-value>)',
        400: 'hsl(var(--color-warntext-400) / <alpha-value>)',
        500: 'hsl(var(--color-warntext-500) / <alpha-value>)',
        600: 'hsl(var(--color-warntext-600) / <alpha-value>)',
        700: 'hsl(var(--color-warntext-700) / <alpha-value>)',
        800: 'hsl(var(--color-warntext-800) / <alpha-value>)',
        900: 'hsl(var(--color-warntext-900) / <alpha-value>)',
        950: 'hsl(var(--color-warntext-950) / <alpha-value>)',
    },
    successtext: {
        50: 'hsl(var(--color-successtext-50) / <alpha-value>)',
        100: 'hsl(var(--color-successtext-100) / <alpha-value>)',
        200: 'hsl(var(--color-successtext-200) / <alpha-value>)',
        300: 'hsl(var(--color-successtext-300) / <alpha-value>)',
        400: 'hsl(var(--color-successtext-400) / <alpha-value>)',
        500: 'hsl(var(--color-successtext-500) / <alpha-value>)',
        600: 'hsl(var(--color-successtext-600) / <alpha-value>)',
        700: 'hsl(var(--color-successtext-700) / <alpha-value>)',
        800: 'hsl(var(--color-successtext-800) / <alpha-value>)',
        900: 'hsl(var(--color-successtext-900) / <alpha-value>)',
        950: 'hsl(var(--color-successtext-950) / <alpha-value>)',
    },
}