import colors from './colors.js';

export const tailwindColors = {
    ...colors,
    inherit: 'inherit',
    current: 'currentColor',
    transparent: 'transparent',
    black: '#000',
    white: '#fff',
    'coffee': {
        '50': 'hsl(var(--color-coffee-50) / <alpha-value>)',
        '100': 'hsl(var(--color-coffee-100) / <alpha-value>)',
        '200': 'hsl(var(--color-coffee-200) / <alpha-value>)',
        '300': 'hsl(var(--color-coffee-300) / <alpha-value>)',
        '400': 'hsl(var(--color-coffee-400) / <alpha-value>)',
        '500': 'hsl(var(--color-coffee-500) / <alpha-value>)',
        '600': 'hsl(var(--color-coffee-600) / <alpha-value>)',
        '700': 'hsl(var(--color-coffee-700) / <alpha-value>)',
        '800': 'hsl(var(--color-coffee-800) / <alpha-value>)',
        '900': 'hsl(var(--color-coffee-900) / <alpha-value>)',
        '950': 'hsl(var(--color-coffee-950) / <alpha-value>)',
    },
    'neutral': {
        '50': 'hsl(var(--color-neutral-50) / <alpha-value>)',
        '100': 'hsl(var(--color-neutral-100) / <alpha-value>)',
        '200': 'hsl(var(--color-neutral-200) / <alpha-value>)',
        '300': 'hsl(var(--color-neutral-300) / <alpha-value>)',
        '400': 'hsl(var(--color-neutral-400) / <alpha-value>)',
        '500': 'hsl(var(--color-neutral-500) / <alpha-value>)',
        '600': 'hsl(var(--color-neutral-600) / <alpha-value>)',
        '700': 'hsl(var(--color-neutral-700) / <alpha-value>)',
        '800': 'hsl(var(--color-neutral-800) / <alpha-value>)',
        '900': 'hsl(var(--color-neutral-900) / <alpha-value>)',
        '950': 'hsl(var(--color-neutral-950) / <alpha-value>)',
    },
    'stone': {
        '50': 'hsl(var(--color-stone-50) / <alpha-value>)',
        '100': 'hsl(var(--color-stone-100) / <alpha-value>)',
        '200': 'hsl(var(--color-stone-200) / <alpha-value>)',
        '300': 'hsl(var(--color-stone-300) / <alpha-value>)',
        '400': 'hsl(var(--color-stone-400) / <alpha-value>)',
        '500': 'hsl(var(--color-stone-500) / <alpha-value>)',
        '600': 'hsl(var(--color-stone-600) / <alpha-value>)',
        '700': 'hsl(var(--color-stone-700) / <alpha-value>)',
        '800': 'hsl(var(--color-stone-800) / <alpha-value>)',
        '900': 'hsl(var(--color-stone-900) / <alpha-value>)',
        '950': 'hsl(var(--color-stone-950) / <alpha-value>)',
    },
    'zinc': {
        '50': 'hsl(var(--color-zinc-50) / <alpha-value>)',
        '100': 'hsl(var(--color-zinc-100) / <alpha-value>)',
        '200': 'hsl(var(--color-zinc-200) / <alpha-value>)',
        '300': 'hsl(var(--color-zinc-300) / <alpha-value>)',
        '400': 'hsl(var(--color-zinc-400) / <alpha-value>)',
        '500': 'hsl(var(--color-zinc-500) / <alpha-value>)',
        '600': 'hsl(var(--color-zinc-600) / <alpha-value>)',
        '700': 'hsl(var(--color-zinc-700) / <alpha-value>)',
        '800': 'hsl(var(--color-zinc-800) / <alpha-value>)',
        '900': 'hsl(var(--color-zinc-900) / <alpha-value>)',
        '950': 'hsl(var(--color-zinc-950) / <alpha-value>)',
    },
    'slate': {
        '50': 'hsl(var(--color-slate-50) / <alpha-value>)',
        '100': 'hsl(var(--color-slate-100) / <alpha-value>)',
        '200': 'hsl(var(--color-slate-200) / <alpha-value>)',
        '300': 'hsl(var(--color-slate-300) / <alpha-value>)',
        '400': 'hsl(var(--color-slate-400) / <alpha-value>)',
        '500': 'hsl(var(--color-slate-500) / <alpha-value>)',
        '600': 'hsl(var(--color-slate-600) / <alpha-value>)',
        '700': 'hsl(var(--color-slate-700) / <alpha-value>)',
        '800': 'hsl(var(--color-slate-800) / <alpha-value>)',
        '900': 'hsl(var(--color-slate-900) / <alpha-value>)',
        '950': 'hsl(var(--color-slate-950) / <alpha-value>)',
    },
    'moss': {
        '50': 'hsl(var(--color-moss-50) / <alpha-value>)',
        '100': 'hsl(var(--color-moss-100) / <alpha-value>)',
        '200': 'hsl(var(--color-moss-200) / <alpha-value>)',
        '300': 'hsl(var(--color-moss-300) / <alpha-value>)',
        '400': 'hsl(var(--color-moss-400) / <alpha-value>)',
        '500': 'hsl(var(--color-moss-500) / <alpha-value>)',
        '600': 'hsl(var(--color-moss-600) / <alpha-value>)',
        '700': 'hsl(var(--color-moss-700) / <alpha-value>)',
        '800': 'hsl(var(--color-moss-800) / <alpha-value>)',
        '900': 'hsl(var(--color-moss-900) / <alpha-value>)',
        '950': 'hsl(var(--color-moss-950) / <alpha-value>)',
    },
    'red': {
        '50': 'hsl(var(--color-red-50) / <alpha-value>)',
        '100': 'hsl(var(--color-red-100) / <alpha-value>)',
        '200': 'hsl(var(--color-red-200) / <alpha-value>)',
        '300': 'hsl(var(--color-red-300) / <alpha-value>)',
        '400': 'hsl(var(--color-red-400) / <alpha-value>)',
        '500': 'hsl(var(--color-red-500) / <alpha-value>)',
        '600': 'hsl(var(--color-red-600) / <alpha-value>)',
        '700': 'hsl(var(--color-red-700) / <alpha-value>)',
        '800': 'hsl(var(--color-red-800) / <alpha-value>)',
        '900': 'hsl(var(--color-red-900) / <alpha-value>)',
        '950': 'hsl(var(--color-red-950) / <alpha-value>)',
    },
    'orange': {
        '50': 'hsl(var(--color-orange-50) / <alpha-value>)',
        '100': 'hsl(var(--color-orange-100) / <alpha-value>)',
        '200': 'hsl(var(--color-orange-200) / <alpha-value>)',
        '300': 'hsl(var(--color-orange-300) / <alpha-value>)',
        '400': 'hsl(var(--color-orange-400) / <alpha-value>)',
        '500': 'hsl(var(--color-orange-500) / <alpha-value>)',
        '600': 'hsl(var(--color-orange-600) / <alpha-value>)',
        '700': 'hsl(var(--color-orange-700) / <alpha-value>)',
        '800': 'hsl(var(--color-orange-800) / <alpha-value>)',
        '900': 'hsl(var(--color-orange-900) / <alpha-value>)',
        '950': 'hsl(var(--color-orange-950) / <alpha-value>)',
    },
    'amber': {
        '50': 'hsl(var(--color-amber-50) / <alpha-value>)',
        '100': 'hsl(var(--color-amber-100) / <alpha-value>)',
        '200': 'hsl(var(--color-amber-200) / <alpha-value>)',
        '300': 'hsl(var(--color-amber-300) / <alpha-value>)',
        '400': 'hsl(var(--color-amber-400) / <alpha-value>)',
        '500': 'hsl(var(--color-amber-500) / <alpha-value>)',
        '600': 'hsl(var(--color-amber-600) / <alpha-value>)',
        '700': 'hsl(var(--color-amber-700) / <alpha-value>)',
        '800': 'hsl(var(--color-amber-800) / <alpha-value>)',
        '900': 'hsl(var(--color-amber-900) / <alpha-value>)',
        '950': 'hsl(var(--color-amber-950) / <alpha-value>)',
    },
    'yellow': {
        '50': 'hsl(var(--color-yellow-50) / <alpha-value>)',
        '100': 'hsl(var(--color-yellow-100) / <alpha-value>)',
        '200': 'hsl(var(--color-yellow-200) / <alpha-value>)',
        '300': 'hsl(var(--color-yellow-300) / <alpha-value>)',
        '400': 'hsl(var(--color-yellow-400) / <alpha-value>)',
        '500': 'hsl(var(--color-yellow-500) / <alpha-value>)',
        '600': 'hsl(var(--color-yellow-600) / <alpha-value>)',
        '700': 'hsl(var(--color-yellow-700) / <alpha-value>)',
        '800': 'hsl(var(--color-yellow-800) / <alpha-value>)',
        '900': 'hsl(var(--color-yellow-900) / <alpha-value>)',
        '950': 'hsl(var(--color-yellow-950) / <alpha-value>)',
    },
    'lime': {
        '50': 'hsl(var(--color-lime-50) / <alpha-value>)',
        '100': 'hsl(var(--color-lime-100) / <alpha-value>)',
        '200': 'hsl(var(--color-lime-200) / <alpha-value>)',
        '300': 'hsl(var(--color-lime-300) / <alpha-value>)',
        '400': 'hsl(var(--color-lime-400) / <alpha-value>)',
        '500': 'hsl(var(--color-lime-500) / <alpha-value>)',
        '600': 'hsl(var(--color-lime-600) / <alpha-value>)',
        '700': 'hsl(var(--color-lime-700) / <alpha-value>)',
        '800': 'hsl(var(--color-lime-800) / <alpha-value>)',
        '900': 'hsl(var(--color-lime-900) / <alpha-value>)',
        '950': 'hsl(var(--color-lime-950) / <alpha-value>)',
    },
    'green': {
        '50': 'hsl(var(--color-green-50) / <alpha-value>)',
        '100': 'hsl(var(--color-green-100) / <alpha-value>)',
        '200': 'hsl(var(--color-green-200) / <alpha-value>)',
        '300': 'hsl(var(--color-green-300) / <alpha-value>)',
        '400': 'hsl(var(--color-green-400) / <alpha-value>)',
        '500': 'hsl(var(--color-green-500) / <alpha-value>)',
        '600': 'hsl(var(--color-green-600) / <alpha-value>)',
        '700': 'hsl(var(--color-green-700) / <alpha-value>)',
        '800': 'hsl(var(--color-green-800) / <alpha-value>)',
        '900': 'hsl(var(--color-green-900) / <alpha-value>)',
        '950': 'hsl(var(--color-green-950) / <alpha-value>)',
    },
    'emerald': {
        '50': 'hsl(var(--color-emerald-50) / <alpha-value>)',
        '100': 'hsl(var(--color-emerald-100) / <alpha-value>)',
        '200': 'hsl(var(--color-emerald-200) / <alpha-value>)',
        '300': 'hsl(var(--color-emerald-300) / <alpha-value>)',
        '400': 'hsl(var(--color-emerald-400) / <alpha-value>)',
        '500': 'hsl(var(--color-emerald-500) / <alpha-value>)',
        '600': 'hsl(var(--color-emerald-600) / <alpha-value>)',
        '700': 'hsl(var(--color-emerald-700) / <alpha-value>)',
        '800': 'hsl(var(--color-emerald-800) / <alpha-value>)',
        '900': 'hsl(var(--color-emerald-900) / <alpha-value>)',
        '950': 'hsl(var(--color-emerald-950) / <alpha-value>)',
    },
    'teal': {
        '50': 'hsl(var(--color-teal-50) / <alpha-value>)',
        '100': 'hsl(var(--color-teal-100) / <alpha-value>)',
        '200': 'hsl(var(--color-teal-200) / <alpha-value>)',
        '300': 'hsl(var(--color-teal-300) / <alpha-value>)',
        '400': 'hsl(var(--color-teal-400) / <alpha-value>)',
        '500': 'hsl(var(--color-teal-500) / <alpha-value>)',
        '600': 'hsl(var(--color-teal-600) / <alpha-value>)',
        '700': 'hsl(var(--color-teal-700) / <alpha-value>)',
        '800': 'hsl(var(--color-teal-800) / <alpha-value>)',
        '900': 'hsl(var(--color-teal-900) / <alpha-value>)',
        '950': 'hsl(var(--color-teal-950) / <alpha-value>)',
    },
    'cyan': {
        '50': 'hsl(var(--color-cyan-50) / <alpha-value>)',
        '100': 'hsl(var(--color-cyan-100) / <alpha-value>)',
        '200': 'hsl(var(--color-cyan-200) / <alpha-value>)',
        '300': 'hsl(var(--color-cyan-300) / <alpha-value>)',
        '400': 'hsl(var(--color-cyan-400) / <alpha-value>)',
        '500': 'hsl(var(--color-cyan-500) / <alpha-value>)',
        '600': 'hsl(var(--color-cyan-600) / <alpha-value>)',
        '700': 'hsl(var(--color-cyan-700) / <alpha-value>)',
        '800': 'hsl(var(--color-cyan-800) / <alpha-value>)',
        '900': 'hsl(var(--color-cyan-900) / <alpha-value>)',
        '950': 'hsl(var(--color-cyan-950) / <alpha-value>)',
    },
    'sky': {
        '50': 'hsl(var(--color-sky-50) / <alpha-value>)',
        '100': 'hsl(var(--color-sky-100) / <alpha-value>)',
        '200': 'hsl(var(--color-sky-200) / <alpha-value>)',
        '300': 'hsl(var(--color-sky-300) / <alpha-value>)',
        '400': 'hsl(var(--color-sky-400) / <alpha-value>)',
        '500': 'hsl(var(--color-sky-500) / <alpha-value>)',
        '600': 'hsl(var(--color-sky-600) / <alpha-value>)',
        '700': 'hsl(var(--color-sky-700) / <alpha-value>)',
        '800': 'hsl(var(--color-sky-800) / <alpha-value>)',
        '900': 'hsl(var(--color-sky-900) / <alpha-value>)',
        '950': 'hsl(var(--color-sky-950) / <alpha-value>)',
    },
    'blue': {
        '50': 'hsl(var(--color-blue-50) / <alpha-value>)',
        '100': 'hsl(var(--color-blue-100) / <alpha-value>)',
        '200': 'hsl(var(--color-blue-200) / <alpha-value>)',
        '300': 'hsl(var(--color-blue-300) / <alpha-value>)',
        '400': 'hsl(var(--color-blue-400) / <alpha-value>)',
        '500': 'hsl(var(--color-blue-500) / <alpha-value>)',
        '600': 'hsl(var(--color-blue-600) / <alpha-value>)',
        '700': 'hsl(var(--color-blue-700) / <alpha-value>)',
        '800': 'hsl(var(--color-blue-800) / <alpha-value>)',
        '900': 'hsl(var(--color-blue-900) / <alpha-value>)',
        '950': 'hsl(var(--color-blue-950) / <alpha-value>)',
    },
    'indigo': {
        '50': 'hsl(var(--color-indigo-50) / <alpha-value>)',
        '100': 'hsl(var(--color-indigo-100) / <alpha-value>)',
        '200': 'hsl(var(--color-indigo-200) / <alpha-value>)',
        '300': 'hsl(var(--color-indigo-300) / <alpha-value>)',
        '400': 'hsl(var(--color-indigo-400) / <alpha-value>)',
        '500': 'hsl(var(--color-indigo-500) / <alpha-value>)',
        '600': 'hsl(var(--color-indigo-600) / <alpha-value>)',
        '700': 'hsl(var(--color-indigo-700) / <alpha-value>)',
        '800': 'hsl(var(--color-indigo-800) / <alpha-value>)',
        '900': 'hsl(var(--color-indigo-900) / <alpha-value>)',
        '950': 'hsl(var(--color-indigo-950) / <alpha-value>)',
    },
    'violet': {
        '50': 'hsl(var(--color-violet-50) / <alpha-value>)',
        '100': 'hsl(var(--color-violet-100) / <alpha-value>)',
        '200': 'hsl(var(--color-violet-200) / <alpha-value>)',
        '300': 'hsl(var(--color-violet-300) / <alpha-value>)',
        '400': 'hsl(var(--color-violet-400) / <alpha-value>)',
        '500': 'hsl(var(--color-violet-500) / <alpha-value>)',
        '600': 'hsl(var(--color-violet-600) / <alpha-value>)',
        '700': 'hsl(var(--color-violet-700) / <alpha-value>)',
        '800': 'hsl(var(--color-violet-800) / <alpha-value>)',
        '900': 'hsl(var(--color-violet-900) / <alpha-value>)',
        '950': 'hsl(var(--color-violet-950) / <alpha-value>)',
    },
    'purple': {
        '50': 'hsl(var(--color-purple-50) / <alpha-value>)',
        '100': 'hsl(var(--color-purple-100) / <alpha-value>)',
        '200': 'hsl(var(--color-purple-200) / <alpha-value>)',
        '300': 'hsl(var(--color-purple-300) / <alpha-value>)',
        '400': 'hsl(var(--color-purple-400) / <alpha-value>)',
        '500': 'hsl(var(--color-purple-500) / <alpha-value>)',
        '600': 'hsl(var(--color-purple-600) / <alpha-value>)',
        '700': 'hsl(var(--color-purple-700) / <alpha-value>)',
        '800': 'hsl(var(--color-purple-800) / <alpha-value>)',
        '900': 'hsl(var(--color-purple-900) / <alpha-value>)',
        '950': 'hsl(var(--color-purple-950) / <alpha-value>)',
    },
    'fuchsia': {
        '50': 'hsl(var(--color-fuchsia-50) / <alpha-value>)',
        '100': 'hsl(var(--color-fuchsia-100) / <alpha-value>)',
        '200': 'hsl(var(--color-fuchsia-200) / <alpha-value>)',
        '300': 'hsl(var(--color-fuchsia-300) / <alpha-value>)',
        '400': 'hsl(var(--color-fuchsia-400) / <alpha-value>)',
        '500': 'hsl(var(--color-fuchsia-500) / <alpha-value>)',
        '600': 'hsl(var(--color-fuchsia-600) / <alpha-value>)',
        '700': 'hsl(var(--color-fuchsia-700) / <alpha-value>)',
        '800': 'hsl(var(--color-fuchsia-800) / <alpha-value>)',
        '900': 'hsl(var(--color-fuchsia-900) / <alpha-value>)',
        '950': 'hsl(var(--color-fuchsia-950) / <alpha-value>)',
    },
    'pink': {
        '50': 'hsl(var(--color-pink-50) / <alpha-value>)',
        '100': 'hsl(var(--color-pink-100) / <alpha-value>)',
        '200': 'hsl(var(--color-pink-200) / <alpha-value>)',
        '300': 'hsl(var(--color-pink-300) / <alpha-value>)',
        '400': 'hsl(var(--color-pink-400) / <alpha-value>)',
        '500': 'hsl(var(--color-pink-500) / <alpha-value>)',
        '600': 'hsl(var(--color-pink-600) / <alpha-value>)',
        '700': 'hsl(var(--color-pink-700) / <alpha-value>)',
        '800': 'hsl(var(--color-pink-800) / <alpha-value>)',
        '900': 'hsl(var(--color-pink-900) / <alpha-value>)',
        '950': 'hsl(var(--color-pink-950) / <alpha-value>)',
    },
    'rose': {
        '50': 'hsl(var(--color-rose-50) / <alpha-value>)',
        '100': 'hsl(var(--color-rose-100) / <alpha-value>)',
        '200': 'hsl(var(--color-rose-200) / <alpha-value>)',
        '300': 'hsl(var(--color-rose-300) / <alpha-value>)',
        '400': 'hsl(var(--color-rose-400) / <alpha-value>)',
        '500': 'hsl(var(--color-rose-500) / <alpha-value>)',
        '600': 'hsl(var(--color-rose-600) / <alpha-value>)',
        '700': 'hsl(var(--color-rose-700) / <alpha-value>)',
        '800': 'hsl(var(--color-rose-800) / <alpha-value>)',
        '900': 'hsl(var(--color-rose-900) / <alpha-value>)',
        '950': 'hsl(var(--color-rose-950) / <alpha-value>)',
    },
    primary: {
        50: 'hsl(var(--color-primary-50) / <alpha-value>)',
        100: 'hsl(var(--color-primary-100) / <alpha-value>)',
        200: 'hsl(var(--color-primary-200) / <alpha-value>)',
        300: 'hsl(var(--color-primary-300) / <alpha-value>)',
        400: 'hsl(var(--color-primary-400) / <alpha-value>)',
        500: 'hsl(var(--color-primary-500) / <alpha-value>)',
        600: 'hsl(var(--color-primary-600) / <alpha-value>)',
        700: 'hsl(var(--color-primary-700) / <alpha-value>)',
        800: 'hsl(var(--color-primary-800) / <alpha-value>)',
        900: 'hsl(var(--color-primary-900) / <alpha-value>)',
        950: 'hsl(var(--color-primary-950) / <alpha-value>)',
    },
    secondary: {
        50: 'hsl(var(--color-secondary-50) / <alpha-value>)',
        100: 'hsl(var(--color-secondary-100) / <alpha-value>)',
        200: 'hsl(var(--color-secondary-200) / <alpha-value>)',
        300: 'hsl(var(--color-secondary-300) / <alpha-value>)',
        400: 'hsl(var(--color-secondary-400) / <alpha-value>)',
        500: 'hsl(var(--color-secondary-500) / <alpha-value>)',
        600: 'hsl(var(--color-secondary-600) / <alpha-value>)',
        700: 'hsl(var(--color-secondary-700) / <alpha-value>)',
        800: 'hsl(var(--color-secondary-800) / <alpha-value>)',
        900: 'hsl(var(--color-secondary-900) / <alpha-value>)',
        950: 'hsl(var(--color-secondary-950) / <alpha-value>)',
    },
    tertiary: {
        50: 'hsl(var(--color-tertiary-50) / <alpha-value>)',
        100: 'hsl(var(--color-tertiary-100) / <alpha-value>)',
        200: 'hsl(var(--color-tertiary-200) / <alpha-value>)',
        300: 'hsl(var(--color-tertiary-300) / <alpha-value>)',
        400: 'hsl(var(--color-tertiary-400) / <alpha-value>)',
        500: 'hsl(var(--color-tertiary-500) / <alpha-value>)',
        600: 'hsl(var(--color-tertiary-600) / <alpha-value>)',
        700: 'hsl(var(--color-tertiary-700) / <alpha-value>)',
        800: 'hsl(var(--color-tertiary-800) / <alpha-value>)',
        900: 'hsl(var(--color-tertiary-900) / <alpha-value>)',
        950: 'hsl(var(--color-tertiary-950) / <alpha-value>)',
    },
    danger: {
        50: 'hsl(var(--color-danger-50) / <alpha-value>)',
        100: 'hsl(var(--color-danger-100) / <alpha-value>)',
        200: 'hsl(var(--color-danger-200) / <alpha-value>)',
        300: 'hsl(var(--color-danger-300) / <alpha-value>)',
        400: 'hsl(var(--color-danger-400) / <alpha-value>)',
        500: 'hsl(var(--color-danger-500) / <alpha-value>)',
        600: 'hsl(var(--color-danger-600) / <alpha-value>)',
        700: 'hsl(var(--color-danger-700) / <alpha-value>)',
        800: 'hsl(var(--color-danger-800) / <alpha-value>)',
        900: 'hsl(var(--color-danger-900) / <alpha-value>)',
        950: 'hsl(var(--color-danger-950) / <alpha-value>)',
    },
    warn: {
        50: 'hsl(var(--color-warn-50) / <alpha-value>)',
        100: 'hsl(var(--color-warn-100) / <alpha-value>)',
        200: 'hsl(var(--color-warn-200) / <alpha-value>)',
        300: 'hsl(var(--color-warn-300) / <alpha-value>)',
        400: 'hsl(var(--color-warn-400) / <alpha-value>)',
        500: 'hsl(var(--color-warn-500) / <alpha-value>)',
        600: 'hsl(var(--color-warn-600) / <alpha-value>)',
        700: 'hsl(var(--color-warn-700) / <alpha-value>)',
        800: 'hsl(var(--color-warn-800) / <alpha-value>)',
        900: 'hsl(var(--color-warn-900) / <alpha-value>)',
        950: 'hsl(var(--color-warn-950) / <alpha-value>)',
    },
    success: {
        50: 'hsl(var(--color-success-50) / <alpha-value>)',
        100: 'hsl(var(--color-success-100) / <alpha-value>)',
        200: 'hsl(var(--color-success-200) / <alpha-value>)',
        300: 'hsl(var(--color-success-300) / <alpha-value>)',
        400: 'hsl(var(--color-success-400) / <alpha-value>)',
        500: 'hsl(var(--color-success-500) / <alpha-value>)',
        600: 'hsl(var(--color-success-600) / <alpha-value>)',
        700: 'hsl(var(--color-success-700) / <alpha-value>)',
        800: 'hsl(var(--color-success-800) / <alpha-value>)',
        900: 'hsl(var(--color-success-900) / <alpha-value>)',
        950: 'hsl(var(--color-success-950) / <alpha-value>)',
    },

    gray: {
        50: 'hsl(var(--color-gray-50) / <alpha-value>)',
        100: 'hsl(var(--color-gray-100) / <alpha-value>)',
        200: 'hsl(var(--color-gray-200) / <alpha-value>)',
        300: 'hsl(var(--color-gray-300) / <alpha-value>)',
        400: 'hsl(var(--color-gray-400) / <alpha-value>)',
        500: 'hsl(var(--color-gray-500) / <alpha-value>)',
        600: 'hsl(var(--color-gray-600) / <alpha-value>)',
        700: 'hsl(var(--color-gray-700) / <alpha-value>)',
        800: 'hsl(var(--color-gray-800) / <alpha-value>)',
        900: 'hsl(var(--color-gray-900) / <alpha-value>)',
        950: 'hsl(var(--color-gray-950) / <alpha-value>)',
    },

    primarytext: {
        50: 'hsl(var(--color-primarytext-50) / <alpha-value>)',
        100: 'hsl(var(--color-primarytext-100) / <alpha-value>)',
        200: 'hsl(var(--color-primarytext-200) / <alpha-value>)',
        300: 'hsl(var(--color-primarytext-300) / <alpha-value>)',
        400: 'hsl(var(--color-primarytext-400) / <alpha-value>)',
        500: 'hsl(var(--color-primarytext-500) / <alpha-value>)',
        600: 'hsl(var(--color-primarytext-600) / <alpha-value>)',
        700: 'hsl(var(--color-primarytext-700) / <alpha-value>)',
        800: 'hsl(var(--color-primarytext-800) / <alpha-value>)',
        900: 'hsl(var(--color-primarytext-900) / <alpha-value>)',
        950: 'hsl(var(--color-primarytext-950) / <alpha-value>)',
    },
    secondarytext: {
        50: 'hsl(var(--color-secondarytext-50) / <alpha-value>)',
        100: 'hsl(var(--color-secondarytext-100) / <alpha-value>)',
        200: 'hsl(var(--color-secondarytext-200) / <alpha-value>)',
        300: 'hsl(var(--color-secondarytext-300) / <alpha-value>)',
        400: 'hsl(var(--color-secondarytext-400) / <alpha-value>)',
        500: 'hsl(var(--color-secondarytext-500) / <alpha-value>)',
        600: 'hsl(var(--color-secondarytext-600) / <alpha-value>)',
        700: 'hsl(var(--color-secondarytext-700) / <alpha-value>)',
        800: 'hsl(var(--color-secondarytext-800) / <alpha-value>)',
        900: 'hsl(var(--color-secondarytext-900) / <alpha-value>)',
        950: 'hsl(var(--color-secondarytext-950) / <alpha-value>)',
    },
    tertiarytext: {
        50: 'hsl(var(--color-tertiarytext-50) / <alpha-value>)',
        100: 'hsl(var(--color-tertiarytext-100) / <alpha-value>)',
        200: 'hsl(var(--color-tertiarytext-200) / <alpha-value>)',
        300: 'hsl(var(--color-tertiarytext-300) / <alpha-value>)',
        400: 'hsl(var(--color-tertiarytext-400) / <alpha-value>)',
        500: 'hsl(var(--color-tertiarytext-500) / <alpha-value>)',
        600: 'hsl(var(--color-tertiarytext-600) / <alpha-value>)',
        700: 'hsl(var(--color-tertiarytext-700) / <alpha-value>)',
        800: 'hsl(var(--color-tertiarytext-800) / <alpha-value>)',
        900: 'hsl(var(--color-tertiarytext-900) / <alpha-value>)',
        950: 'hsl(var(--color-tertiarytext-950) / <alpha-value>)',
    },
    dangertext: {
        50: 'hsl(var(--color-dangertext-50) / <alpha-value>)',
        100: 'hsl(var(--color-dangertext-100) / <alpha-value>)',
        200: 'hsl(var(--color-dangertext-200) / <alpha-value>)',
        300: 'hsl(var(--color-dangertext-300) / <alpha-value>)',
        400: 'hsl(var(--color-dangertext-400) / <alpha-value>)',
        500: 'hsl(var(--color-dangertext-500) / <alpha-value>)',
        600: 'hsl(var(--color-dangertext-600) / <alpha-value>)',
        700: 'hsl(var(--color-dangertext-700) / <alpha-value>)',
        800: 'hsl(var(--color-dangertext-800) / <alpha-value>)',
        900: 'hsl(var(--color-dangertext-900) / <alpha-value>)',
        950: 'hsl(var(--color-dangertext-950) / <alpha-value>)',
    },
    warntext: {
        50: 'hsl(var(--color-warntext-50) / <alpha-value>)',
        100: 'hsl(var(--color-warntext-100) / <alpha-value>)',
        200: 'hsl(var(--color-warntext-200) / <alpha-value>)',
        300: 'hsl(var(--color-warntext-300) / <alpha-value>)',
        400: 'hsl(var(--color-warntext-400) / <alpha-value>)',
        500: 'hsl(var(--color-warntext-500) / <alpha-value>)',
        600: 'hsl(var(--color-warntext-600) / <alpha-value>)',
        700: 'hsl(var(--color-warntext-700) / <alpha-value>)',
        800: 'hsl(var(--color-warntext-800) / <alpha-value>)',
        900: 'hsl(var(--color-warntext-900) / <alpha-value>)',
        950: 'hsl(var(--color-warntext-950) / <alpha-value>)',
    },
    successtext: {
        50: 'hsl(var(--color-successtext-50) / <alpha-value>)',
        100: 'hsl(var(--color-successtext-100) / <alpha-value>)',
        200: 'hsl(var(--color-successtext-200) / <alpha-value>)',
        300: 'hsl(var(--color-successtext-300) / <alpha-value>)',
        400: 'hsl(var(--color-successtext-400) / <alpha-value>)',
        500: 'hsl(var(--color-successtext-500) / <alpha-value>)',
        600: 'hsl(var(--color-successtext-600) / <alpha-value>)',
        700: 'hsl(var(--color-successtext-700) / <alpha-value>)',
        800: 'hsl(var(--color-successtext-800) / <alpha-value>)',
        900: 'hsl(var(--color-successtext-900) / <alpha-value>)',
        950: 'hsl(var(--color-successtext-950) / <alpha-value>)',
    },
}